version: '3.7'

services:
  httpd:
    container_name: httpd
    build: ../httpd/build
    volumes:
      - ../httpd/conf/:/etc/httpd/conf/
      - ../httpd/conf.d/:/etc/httpd/conf.d/
    ports:
      - "80:80"
