version: '3.7'

services:
  tomcat1:
    container_name: tomcat1
    build: ../tomcat/build1
    volumes:
      - ../target/:/usr/local/tomcat/webapps/
      - ../tomcat/conf1/:/usr/local/tomcat/conf/
    expose:
      - "8009"
    ports:
      - "8888:8080"
  tomcat2:
    container_name: tomcat2
    build: ../tomcat/build2
    volumes:
      - ../target/:/usr/local/tomcat/webapps/
      - ../tomcat/conf2/:/usr/local/tomcat/conf/
    expose:
      - "8019"
    ports:
      - "9999:8080"
